apiVersion: argoproj.io/v1alpha1
kind: Application
labels:
  component-id: data-governor
metadata:
  name: data-governor-gitops
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: data-governor
    helm:
      valuesObject:
        global:
          blockStorageClass: ocs-external-storagecluster-ceph-rbd
          fileStorageClass: ocs-external-storagecluster-cephfs
          installConfigImageDigest: sha256:4f6f08222f49b94ab2c5dc085dbf7ecc32ef77c01a7715568b50dfc1443cdadf
          installConfigImageName: cpopen/cpd/olm-utils-v4
          installConfigImagePullPrefix: cp.icr.io
          instanceNamespace: gitops-instance
          licenseAccept: true
          operatorNamespace: gitops-operator
          releaseVersion: 5.3.1
    path: ''
    repoURL: https://raw.githubusercontent.com/IBM/charts/master/repo/ibm-helm
    targetRevision: 8.1.0+20260223.191904.312
