apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: db2aaservice-gitops
  namespace: openshift-gitops
  labels:
    scope: namespace
    product: software-hub
spec:
  ignoreDifferences:
    - kind: "*"
      group: "*"
      jsonPointers:
        - /metadata/annotations
        - /metadata/labels
  destination:
    name: ''
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://raw.githubusercontent.com/IBM/charts/master/repo/ibm-helm
    targetRevision: 5.3.1+20260215.235516.3673.4966
    chart: db2aaservice
    helm:
      valuesObject:
        global:
          licenseAccept: true
          operatorNamespace: gitops-operator
          instanceNamespace: gitops-instance
          blockStorageClass: ocs-external-storagecluster-ceph-rbd
          fileStorageClass: ocs-external-storagecluster-cephfs
          imagePullPrefix: icr.io
          imagePullSecret: ibm-entitlement-key
        db2aaservice:
          deployCR: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
