apiVersion: argoproj.io/v1alpha1
kind: Application
labels:
  component-id: ibm-usage-metering
metadata:
  name: ibm-usage-metering-cluster-gitops
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: ibm-usage-metering-cluster-scoped
    helm:
      valuesObject:
        global:
          blockStorageClass: ocs-external-storagecluster-ceph-rbd
          fileStorageClass: ocs-external-storagecluster-cephfs
          installConfigImageDigest: sha256:3f03ae78e4101a63c089980ffb5eef0db51b8897afd44b609ce409897e5f0827
          installConfigImageName: cp/cpd/olm-utils-premium-v4
          installConfigImagePullPrefix: cp.icr.io
          instanceNamespace: gitops-instance
          licenseAccept: true
          operatorNamespace: gitops-operator
          releaseVersion: 5.3.1
    path: ''
    repoURL: https://raw.githubusercontent.com/IBM/charts/master/repo/ibm-helm
    targetRevision: 1.0.4+20260210.110820.0
