apiVersion: argoproj.io/v1alpha1
kind: Application
labels:
  component-id: cpfs
metadata:
  name: ibm-namespace-scope-operator-cluster-gitops
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: ibm-namespace-scope-operator-cluster-scoped
    helm:
      valuesObject:
        global:
          blockStorageClass: ocs-external-storagecluster-ceph-rbd
          fileStorageClass: ocs-external-storagecluster-cephfs
          installConfigImageDigest: sha256:3f03ae78e4101a63c089980ffb5eef0db51b8897afd44b609ce409897e5f0827
          installConfigImageName: cp/cpd/olm-utils-premium-v4
          installConfigImagePullPrefix: cp.icr.io
          instanceNamespace: gitops-instance
          licenseAccept: true
          operatorNamespace: gitops-operator
          releaseVersion: 5.3.1
    path: ''
    repoURL: https://howard-luo.github.io/non-olm-cp4d-gitops-531/repos
    targetRevision: 4.3.4+20260203.110835.0
