apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ibm-events-operator-gitops
  namespace: openshift-gitops
  labels:
    scope: cluster
    product: software-hub
spec:
  ignoreDifferences:
    - kind: "*"
      group: "*"
      jsonPointers:
        - /metadata/annotations
        - /metadata/labels
  destination:
    name: ''
    namespace: gitops-instance ## this chart will deployed on instance namespace
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://raw.githubusercontent.com/IBM/charts/master/repo/ibm-helm
    targetRevision: 6.0.0+20260126.110734.0
    chart: ibm-events-operator
    helm:
      valuesObject:
        watchNamespaces: [gitops-instance]
        # watchNamespaces: [gitops-operator,gitops-instance]
        # watchAnyNamespace: true
        # kafka:
        #   image:
        #     name: "kafka:latest-kafka-4.1.1,3.7.0=quay.io/strimzi/kafka:latest-kafka-3.7.0,3.8.0=quay.io/strimzi/kafka:latest-kafka-3.8.0"
        kafka:
          image:
            name: "kafka:latest-kafka-4.1.1,4.1.0=quay.io/strimzi/kafka:latest-kafka-4.1.0,4.2.0=quay.io/strimzi/kafka"
        kafkaConnect:
          image:
            name: "kafka:latest-kafka-4.1.1,4.1.0=quay.io/strimzi/kafka:latest-kafka-4.1.0,4.2.0=quay.io/strimzi/kafka"
        kafkaMirrorMaker2:
          image:
            name: "kafka:latest-kafka-4.1.1,4.1.0=quay.io/strimzi/kafka:latest-kafka-4.1.0,4.2.0=quay.io/strimzi/kafka"
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
