apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openpages-gitops
  namespace: openshift-gitops
  labels:
    scope: namespace
    product: software-hub
spec:
  ignoreDifferences:
    - kind: "*"
      group: "*"
      jsonPointers:
        - /metadata/annotations
        - /metadata/labels
  destination:
    name: ''
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://raw.githubusercontent.com/IBM/charts/master/repo/ibm-helm/index.yaml
    targetRevision: 10.1.0+20260211.115519.913102730
    chart: openpages
    helm:
      valuesObject:
        global:
          licenseAccept: true
          operatorNamespace: gitops-operator
          instanceNamespace: gitops-instance
          blockStorageClass: ocs-external-storagecluster-ceph-rbd
          fileStorageClass: ocs-external-storagecluster-cephfs
          imagePullPrefix: icr.io
          imagePullSecret: ibm-entitlement-key
        openpages:
          deployCR: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
