apiVersion: argoproj.io/v1alpha1
kind: Application
labels:
  component-id: watsonx-data
metadata:
  name: watsonx-data-cluster-gitops
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: watsonx-data-cluster-scoped
    helm:
      valuesObject:
        global:
          blockStorageClass: ocs-external-storagecluster-ceph-rbd
          fileStorageClass: ocs-external-storagecluster-cephfs
          installConfigImageDigest: sha256:3f03ae78e4101a63c089980ffb5eef0db51b8897afd44b609ce409897e5f0827
          installConfigImageName: cp/cpd/olm-utils-premium-v4
          installConfigImagePullPrefix: cp.icr.io
          instanceNamespace: gitops-instance
          licenseAccept: true
          operatorNamespace: gitops-operator
          releaseVersion: 5.3.1
    path: ''
    repoURL: https://howard-luo.github.io/non-olm-cp4d-gitops-531/repos
    targetRevision: 6.1.0+20260212.012337.151
