apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cpd-platform-gitops
  namespace: openshift-gitops
  labels:
    scope: namespace
    product: software-hub
spec:
  destination:
    name: ''
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://raw.githubusercontent.com/IBM/charts/master/repo/ibm-helm
    targetRevision: 5.10.3+20260706.110612.12
    chart: cpd-platform
    helm:
      valuesObject:
        global:
          licenseAccept: true
          releaseVersion: 5.4.0
          operatorNamespace: gitops-operator
          instanceNamespace: gitops-instance
          blockStorageClass: ocs-external-storagecluster-ceph-rbd
          fileStorageClass: ocs-external-storagecluster-cephfs
          # imagePullPrefix: icr.io
          imagePullSecret: ibm-entitlement-key
          installConfigImageDigest: sha256:4f6f08222f49b94ab2c5dc085dbf7ecc32ef77c01a7715568b50dfc1443cdadf
          installConfigImageName: cpopen/cpd/olm-utils-v4
          installConfigImagePullPrefix: cp.icr.io
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
