apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cs-gitops
  namespace: openshift-gitops
  labels:
    scope: namespace
    product: software-hub
spec:
  destination:
    name: ''
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://raw.githubusercontent.com/IBM/charts/master/repo/ibm-helm
    targetRevision: 4.19.1+20260612.165329.0
    chart: ibm-common-service-operator
    helm:
      valuesObject:
        global:
          licenseAccept: true
          releaseVersion: 5.4,0
          operatorNamespace: gitops-operator
          instanceNamespace: gitops-instance
          blockStorageClass: ocs-external-storagecluster-ceph-rbd
          fileStorageClass: ocs-external-storagecluster-cephfs
          imagePullPrefix: icr.io
          imagePullSecret: ibm-entitlement-key
          scaleConfig: small
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
