apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: im-gitops
  namespace: openshift-gitops
  labels:
    scope: namespace
    product: software-hub
spec:
  destination:
    name: ''
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://raw.githubusercontent.com/IBM/charts/master/repo/ibm-helm/index.yaml
    targetRevision: 4.18.0+20260527.142210.0
    chart: ibm-iam-operator
    helm:
      valuesObject:
        global:
          licenseAccept: true
          operatorNamespace: gitops-operator
          instanceNamespace: gitops-instance
          tetheredNamespaces: []
          releaseVersion: 5.4.0
          blockStorageClass: ocs-external-storagecluster-ceph-rbd
          fileStorageClass: ocs-external-storagecluster-cephfs
          # imagePullPrefix: icr.io
          imagePullSecret: ibm-entitlement-key
          installConfigImageDigest: sha256:3f03ae78e4101a63c089980ffb5eef0db51b8897afd44b609ce409897e5f0827
          installConfigImageName: cp/cpd/olm-utils-premium-v4
          installConfigImagePullPrefix: cp.icr.io
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
