apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zen-gitops
  namespace: openshift-gitops
  labels:
    scope: namespace
    product: software-hub
spec:
  ignoreDifferences:
    - kind: "*"
      group: "*"
      jsonPointers:
        - /metadata/annotations
        - /metadata/labels
  destination:
    name: ''
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://raw.githubusercontent.com/IBM/charts/master/repo/ibm-helm
    targetRevision: 6.10.3+20260713.120632.33
    chart: zen
    helm:
      valuesObject:
        global:
          licenseAccept: true
          operatorNamespace: gitops-operator
          instanceNamespace: gitops-instance
          blockStorageClass: ocs-external-storagecluster-ceph-rbd
          fileStorageClass: ocs-external-storagecluster-cephfs
          # imagePullPrefix: icr.io
          imagePullSecret: ibm-entitlement-key
          installConfigImageDigest: sha256:4f6f08222f49b94ab2c5dc085dbf7ecc32ef77c01a7715568b50dfc1443cdadf
          installConfigImageName: cpopen/cpd/olm-utils-v4
          installConfigImagePullPrefix: cp.icr.io
          releaseVersion: 5.4.0
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
