apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cpd-platform-cluster-gitops
  namespace: openshift-gitops
  labels:
    scope: cluster
    product: software-hub
spec:
  destination:
    name: ''
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://raw.githubusercontent.com/IBM/charts/master/repo/ibm-helm
    targetRevision: 5.10.0+20260526.162139.68
    chart: cpd-platform-cluster-scoped
    helm:
      valuesObject:
        global:
          operatorNamespace: gitops-operator
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
