apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cs-cluster-gitops
  namespace: openshift-gitops
  labels:
    scope: cluster
    product: software-hub
spec:
  destination:
    name: ''
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://raw.githubusercontent.com/IBM/charts/master/repo/ibm-helm/index.yaml
    chart: ibm-common-service-operator-cluster-scoped
    targetRevision: 4.19.1+20260612.165329.0
    helm:
      valuesObject:
        global:
          operatorNamespace: gitops-operator
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
