apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zen-cluster-gitops
  namespace: openshift-gitops
  labels:
    scope: cluster
    product: software-hub
spec:
  destination:
    name: ''
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://raw.githubusercontent.com/IBM/charts/master/repo/ibm-helm/index.yaml
    targetRevision: 6.10.1+20260609.224006.17
    chart: zen-cluster-scoped
    helm:
      valuesObject:
        global:
          operatorNamespace: gitops-operator
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
